version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    image: akanksha/code-review-backend:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/code-reviewer
      - ALLOWED_ORIGINS=http://frontend:5173,http://localhost:3000
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: akanksha/code-review-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000/api
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

