name: Deploy MERN App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Node.js
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            nvm use 18

            # Install PM2 and Nginx
            npm install -g pm2
            sudo apt-get update
            sudo apt-get install -y nginx

            # ===== Backend Deployment =====
            cd /home/ubuntu/code-reviewer/Backend
            npm install
            echo "GEMINI_API_KEY=${{ secrets.GEMINI_KEY }}" > .env
            pm2 stop backend-app || true
            pm2 start server.js --name backend-app --watch
            pm2 save

            # ===== Frontend Deployment =====
            cd /home/ubuntu/code-reviewer/Frontend
            npm install
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/
            sudo systemctl restart nginx

            sudo cp -r build/* /var/www/html/
            
            # Restart Nginx to serve the updated frontend files
            sudo systemctl restart nginx
