name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Deploy Backend
      - name: Deploy Backend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to backend folder
            cd /home/ubuntu/code-reviewer/BackEnd
            
            # Install dependencies and set up environment variables
            npm install
            echo "GOOGLE_GEMINI_KEY=your_gemini_api_key_here" > .env
            
            # Start backend server using PM2
            pm2 stop all || true
            pm2 start server.js --name backend-app --watch
            
            # Save PM2 process list to start on reboot
            pm2 save

      # Step 4: Deploy Frontend
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to frontend folder
            cd /home/ubuntu/code-reviewer/Frontend
            
            # Install dependencies and build the frontend
            npm install
            npm run build
            
            # Deploy build files to Nginx's web root directory
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/
            
            # Restart Nginx to serve the updated frontend files
            sudo systemctl restart nginx
