name: code-reviewer

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            nvm use 18

            # Backend setup
            cd ~/code-reviewer/Backend
            npm install
            echo "GEMINI_API_KEY=${{ secrets.GEMINI_KEY }}" > .env
            pm2 stop backend-app || true
            pm2 start server.js --name backend-app --watch
            pm2 save

            # Frontend setup
            cd ~/code-reviewer/Frontend
            npm install
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx
